[cerebrium.deployment]
name = "my-first-project"
python_version = "3.13"
docker_base_image_url = "debian:bookworm-slim"
disable_auth = false

# More reliable inclusion/exclusion
include = ["*.py", "requirements.txt", "cerebrium.toml", "pytorch_model_weights.pth","mtailor.onnx"]
exclude = ["__pycache__/*", "*.pyc", ".*"]  # Fixed exclusion pattern for __pycache__

[cerebrium.hardware]
cpu = 2.0
memory = 12.0
compute = "CPU"

[cerebrium.scaling]
min_replicas = 0
max_replicas = 5
cooldown = 30
replica_concurrency = 1
response_grace_period = 900
scaling_metric = "concurrency_utilization"
scaling_target = 100
scaling_buffer = 0
roll_out_duration_seconds = 0
